"""Typed ElevenLabs Music adapter with a durable B2 output gate.

The pinned Genblaze ElevenLabs connector only implements TTS and sound effects,
not the dedicated Music API. This direct adapter therefore uses the official
ElevenLabs SDK for the wire contract and does not report success until the exact
generated bytes have been stored in and re-read from B2.
"""

from __future__ import annotations

import asyncio
import hashlib
import uuid
from collections.abc import Callable, Iterator, Mapping
from contextlib import AbstractContextManager
from dataclasses import dataclass, field
from typing import Any, Protocol

import httpx
from elevenlabs.client import ElevenLabs
from elevenlabs.core.api_error import ApiError
from pydantic import BaseModel, ConfigDict, Field, model_validator
from takegraph_domain.errors import (
    AssetVerificationError,
    FeatureNotConfiguredError,
    InvalidSourceError,
    ProviderAuthError,
    ProviderQuotaError,
    ProviderUnavailableError,
)
from takegraph_domain.storage.keys import content_address
from takegraph_infrastructure.b2 import B2Settings, B2Store, StoredObject

SUPPORTED_MUSIC_MODELS = frozenset({"music_v1", "music_v2"})


@dataclass(frozen=True, slots=True)
class ElevenLabsMusicSettings:
    api_key: str = field(repr=False)
    music_model: str
    output_format: str = "mp3_48000_192"

    @classmethod
    def from_env(cls, env: Mapping[str, str]) -> ElevenLabsMusicSettings:
        names = ("ELEVENLABS_API_KEY", "ELEVENLABS_MUSIC_MODEL")
        missing = [name for name in names if not env.get(name)]
        if missing:
            raise FeatureNotConfiguredError(
                f"ElevenLabs music is not configured: missing {', '.join(missing)}.",
                details={"missing": missing},
            )
        model = env["ELEVENLABS_MUSIC_MODEL"]
        if model not in SUPPORTED_MUSIC_MODELS:
            raise FeatureNotConfiguredError(
                f"ElevenLabs music model {model!r} is unsupported by the pinned SDK."
            )
        output_format = env.get("ELEVENLABS_MUSIC_OUTPUT_FORMAT") or "mp3_48000_192"
        if not output_format.startswith("mp3_"):
            raise FeatureNotConfiguredError(
                "ElevenLabs music output must be MP3 until the media normalizer supports more."
            )
        return cls(
            api_key=env["ELEVENLABS_API_KEY"],
            music_model=model,
            output_format=output_format,
        )


class MusicGenerationRequest(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    organization_id: uuid.UUID
    project_id: uuid.UUID
    build_node_id: uuid.UUID
    attempt_id: uuid.UUID
    prompt: str = Field(min_length=1, max_length=5_000)
    model: str
    duration_ms: int = Field(ge=3_000, le=600_000)
    idempotency_key: str = Field(pattern=r"^[0-9a-f]{64}$")
    timeout_seconds: int = Field(default=180, ge=1, le=600)
    force_instrumental: bool = True

    @model_validator(mode="after")
    def require_supported_model(self) -> MusicGenerationRequest:
        if self.model not in SUPPORTED_MUSIC_MODELS:
            raise ValueError("music model must be music_v1 or music_v2")
        return self


class MusicGenerationResult(BaseModel):
    model_config = ConfigDict(frozen=True, extra="forbid")

    provider_request_id: str | None
    model: str
    b2_key: str = Field(min_length=1)
    sha256: str = Field(pattern=r"^[0-9a-f]{64}$")
    size_bytes: int = Field(gt=0)
    media_type: str


class MusicGenerator(Protocol):
    async def generate(self, request: MusicGenerationRequest) -> MusicGenerationResult: ...


class MusicStore(Protocol):
    @property
    def prefix(self) -> str: ...

    def store_bytes(
        self,
        key: str,
        data: bytes,
        *,
        content_type: str,
        metadata: dict[str, str] | None = None,
    ) -> StoredObject: ...

    def verify(self, key: str, *, expected_sha256: str) -> bool: ...


class RawMusicResponse(Protocol):
    headers: dict[str, str]
    data: Iterator[bytes]


RawCompose = Callable[..., AbstractContextManager[RawMusicResponse]]
ClientFactory = Callable[[str], Any]


class ElevenLabsMusicGateway:
    def __init__(
        self,
        settings: ElevenLabsMusicSettings,
        store: MusicStore,
        *,
        client_factory: ClientFactory | None = None,
    ) -> None:
        self._settings = settings
        self._store = store
        self._client_factory = client_factory or (lambda api_key: ElevenLabs(api_key=api_key))

    @classmethod
    def from_env(cls, env: Mapping[str, str]) -> ElevenLabsMusicGateway:
        settings = ElevenLabsMusicSettings.from_env(env)
        store = B2Store(B2Settings.from_env(dict(env)))
        return cls(settings, store)

    async def generate(self, request: MusicGenerationRequest) -> MusicGenerationResult:
        if request.model != self._settings.music_model:
            raise FeatureNotConfiguredError(
                "Requested music model does not match the configured provider policy."
            )
        try:
            return await asyncio.to_thread(self._generate_sync, request)
        except ApiError as exc:
            if exc.status_code in (401, 403):
                raise ProviderAuthError("ElevenLabs rejected the configured credential.") from exc
            if exc.status_code == 429:
                raise ProviderQuotaError("ElevenLabs music quota was reached.") from exc
            if exc.status_code in (400, 422):
                raise InvalidSourceError("ElevenLabs rejected the music request.") from exc
            raise ProviderUnavailableError(
                f"ElevenLabs music failed with HTTP {exc.status_code or 'unknown'}."
            ) from exc
        except httpx.HTTPError as exc:
            raise ProviderUnavailableError("ElevenLabs music was unreachable.") from exc

    def _generate_sync(self, request: MusicGenerationRequest) -> MusicGenerationResult:
        client = self._client_factory(self._settings.api_key)
        compose: RawCompose = client.music.with_raw_response.compose
        with compose(
            prompt=request.prompt,
            music_length_ms=request.duration_ms,
            model_id=request.model,
            force_instrumental=request.force_instrumental,
            output_format=self._settings.output_format,
            request_options={
                "timeout_in_seconds": request.timeout_seconds,
                "max_retries": 0,
            },
        ) as response:
            payload = b"".join(response.data)
            request_id = response.headers.get("request-id") or response.headers.get("x-request-id")
        if not payload:
            raise ProviderUnavailableError("ElevenLabs music completed without audio bytes.")
        if not payload.startswith((b"ID3", b"\xff\xfb", b"\xff\xf3", b"\xff\xf2")):
            raise InvalidSourceError("ElevenLabs music response is not an MP3 stream.")

        digest = hashlib.sha256(payload).hexdigest()
        key = content_address(
            organization_id=request.organization_id,
            sha256=digest,
            extension="mp3",
            prefix=self._store.prefix,
        )
        stored = self._store.store_bytes(
            key,
            payload,
            content_type="audio/mpeg",
            metadata={
                "attempt_id": str(request.attempt_id),
                "stable_key": "audio.music",
                "model": request.model,
                "idempotency_key": request.idempotency_key,
            },
        )
        if not self._store.verify(key, expected_sha256=stored.sha256):
            raise AssetVerificationError("Stored music bytes failed B2 re-verification.")
        return MusicGenerationResult(
            provider_request_id=request_id,
            model=request.model,
            b2_key=stored.key,
            sha256=stored.sha256,
            size_bytes=stored.size_bytes,
            media_type=stored.content_type,
        )


__all__ = [
    "ElevenLabsMusicGateway",
    "ElevenLabsMusicSettings",
    "MusicGenerationRequest",
    "MusicGenerationResult",
    "MusicGenerator",
    "SUPPORTED_MUSIC_MODELS",
]
