"""core schema

Revision ID: a6ef8dba4499
Revises:
Create Date: 2026-08-02 14:09:09.992459
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "a6ef8dba4499"
down_revision: str | None = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_user_id", sa.UUID(), nullable=True),
        sa.Column("actor_kind", sa.String(length=16), nullable=False),
        sa.Column("effective_role", sa.String(length=16), nullable=True),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=True),
        sa.Column("before_ref", sa.String(length=128), nullable=True),
        sa.Column("after_ref", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(
        "ix_audit_project_time", "audit_log", ["project_id", "occurred_at"], unique=False
    )
    op.create_table(
        "b2_webhook_messages",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("signature_version", sa.String(length=8), nullable=False),
        sa.Column("body_sha256", sa.String(length=64), nullable=False),
        sa.Column("signature_valid", sa.Boolean(), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("processed_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_b2_webhook_messages")),
        sa.UniqueConstraint("body_sha256", name=op.f("uq_b2_webhook_messages_body_sha256")),
    )
    op.create_table(
        "domain_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("build_id", sa.UUID(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("correlation_id", sa.UUID(), nullable=True),
        sa.Column(
            "occurred_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("realtime_published_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_domain_events")),
        sa.UniqueConstraint("event_id", name=op.f("uq_domain_events_event_id")),
    )
    op.create_index(
        "ix_domain_events_build_seq", "domain_events", ["build_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_domain_events_project_seq", "domain_events", ["project_id", "sequence"], unique=False
    )
    op.create_index(
        "ix_domain_events_unpublished",
        "domain_events",
        ["sequence"],
        unique=False,
        postgresql_where=sa.text("realtime_published_at is null"),
    )
    op.create_table(
        "graph_templates",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("schema_version", sa.String(length=8), nullable=False),
        sa.Column("definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_templates")),
        sa.UniqueConstraint("key", "version", name=op.f("uq_graph_templates_key_version")),
    )
    op.create_table(
        "organizations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_table(
        "provider_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_provider_policies")),
        sa.UniqueConstraint(
            "organization_id",
            "key",
            "version",
            name=op.f("uq_provider_policies_organization_id_key_version"),
        ),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("external_subject", sa.String(length=255), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("external_subject", name=op.f("uq_users_external_subject")),
    )
    op.create_table(
        "validation_policies",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=True),
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("definition_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validation_policies")),
        sa.UniqueConstraint(
            "organization_id",
            "key",
            "version",
            name=op.f("uq_validation_policies_organization_id_key_version"),
        ),
    )
    op.create_table(
        "work_items",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=48), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("build_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "available_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("lease_owner", sa.String(length=64), nullable=True),
        sa.Column("lease_expires_at", sa.DateTime(), nullable=True),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=128), nullable=False),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_work_items")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_work_items_dedupe_key")),
    )
    op.create_index(
        "ix_work_items_claimable",
        "work_items",
        ["available_at", "priority"],
        unique=False,
        postgresql_where=sa.text("status in ('QUEUED', 'RETRY_WAIT')"),
    )
    op.create_table(
        "assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("mime_type", sa.String(length=128), nullable=False),
        sa.Column("media_kind", sa.String(length=24), nullable=False),
        sa.Column("b2_bucket", sa.String(length=128), nullable=False),
        sa.Column("b2_key", sa.String(length=1024), nullable=False),
        sa.Column("storage_version_id", sa.String(length=128), nullable=True),
        sa.Column("metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("derived_from_asset_id", sa.UUID(), nullable=True),
        sa.Column("verified_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_assets_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint(
            "organization_id", "sha256", name=op.f("uq_assets_organization_id_sha256")
        ),
    )
    op.create_table(
        "b2_object_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dedupe_key", sa.String(length=256), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("bucket", sa.String(length=128), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("object_version_id", sa.String(length=128), nullable=True),
        sa.Column("object_size", sa.Integer(), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("trigger_source", sa.String(length=24), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["b2_webhook_messages.id"],
            name=op.f("fk_b2_object_events_message_id_b2_webhook_messages"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_b2_object_events")),
        sa.UniqueConstraint("dedupe_key", name=op.f("uq_b2_object_events_dedupe_key")),
    )
    op.create_index(
        "ix_b2_object_events_status_time",
        "b2_object_events",
        ["status", "event_timestamp"],
        unique=False,
    )
    op.create_table(
        "memberships",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_memberships_organization_id_organizations"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_memberships_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_memberships")),
        sa.UniqueConstraint(
            "organization_id", "user_id", name=op.f("uq_memberships_organization_id_user_id")
        ),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("active_revision_id", sa.UUID(), nullable=True),
        sa.Column("active_release_id", sa.UUID(), nullable=True),
        sa.Column("is_demo", sa.Boolean(), nullable=False),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_projects_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_projects")),
        sa.UniqueConstraint(
            "organization_id", "slug", name=op.f("uq_projects_organization_id_slug")
        ),
    )
    op.create_table(
        "approvals",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("target_type", sa.String(length=32), nullable=False),
        sa.Column("target_id", sa.UUID(), nullable=False),
        sa.Column("decision", sa.String(length=16), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_approvals_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approvals")),
    )
    op.create_table(
        "fault_rules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("node_stable_key", sa.String(length=128), nullable=False),
        sa.Column("fault_type", sa.String(length=32), nullable=False),
        sa.Column("remaining_uses", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_fault_rules_project_id_projects"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fault_rules")),
    )
    op.create_table(
        "project_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("revision_no", sa.Integer(), nullable=False),
        sa.Column("parent_revision_id", sa.UUID(), nullable=True),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_project_revisions_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_project_revisions")),
        sa.UniqueConstraint(
            "project_id",
            "canonical_hash",
            name=op.f("uq_project_revisions_project_id_canonical_hash"),
        ),
        sa.UniqueConstraint(
            "project_id", "revision_no", name=op.f("uq_project_revisions_project_id_revision_no")
        ),
    )
    op.create_table(
        "sources",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_sources_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sources")),
        sa.UniqueConstraint(
            "project_id", "stable_key", name=op.f("uq_sources_project_id_stable_key")
        ),
    )
    op.create_table(
        "change_sets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("base_revision_id", sa.UUID(), nullable=False),
        sa.Column("patch_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["base_revision_id"],
            ["project_revisions.id"],
            name=op.f("fk_change_sets_base_revision_id_project_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_change_sets_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_change_sets")),
    )
    op.create_table(
        "graph_revisions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_revision_id", sa.UUID(), nullable=False),
        sa.Column("template_id", sa.UUID(), nullable=False),
        sa.Column("canonical_hash", sa.String(length=64), nullable=False),
        sa.Column("compiler_version", sa.String(length=16), nullable=False),
        sa.Column(
            "compiled_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["project_revision_id"],
            ["project_revisions.id"],
            name=op.f("fk_graph_revisions_project_revision_id_project_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["template_id"],
            ["graph_templates.id"],
            name=op.f("fk_graph_revisions_template_id_graph_templates"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_revisions")),
        sa.UniqueConstraint(
            "project_revision_id", name=op.f("uq_graph_revisions_project_revision_id")
        ),
    )
    op.create_table(
        "source_versions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("source_id", sa.UUID(), nullable=False),
        sa.Column("revision_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("normalized_text", sa.Text(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["sources.id"],
            name=op.f("fk_source_versions_source_id_sources"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_versions")),
    )
    op.create_table(
        "builds",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("project_revision_id", sa.UUID(), nullable=False),
        sa.Column("graph_revision_id", sa.UUID(), nullable=False),
        sa.Column("impact_plan_id", sa.UUID(), nullable=True),
        sa.Column("parent_build_id", sa.UUID(), nullable=True),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("total_nodes", sa.Integer(), nullable=False),
        sa.Column("reused_nodes", sa.Integer(), nullable=False),
        sa.Column("rebuilt_nodes", sa.Integer(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("provider_reported_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("is_fixture", sa.Boolean(), nullable=False),
        sa.Column("cancel_requested_at", sa.DateTime(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["graph_revision_id"],
            ["graph_revisions.id"],
            name=op.f("fk_builds_graph_revision_id_graph_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_builds_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_revision_id"],
            ["project_revisions.id"],
            name=op.f("fk_builds_project_revision_id_project_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_builds")),
    )
    op.create_index(
        "ix_builds_project_created", "builds", ["project_id", "created_at"], unique=False
    )
    op.create_table(
        "graph_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_revision_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("node_type", sa.String(length=32), nullable=False),
        sa.Column("spec_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("spec_hash", sa.String(length=64), nullable=False),
        sa.Column("provider_policy_id", sa.UUID(), nullable=True),
        sa.Column("validation_policy_id", sa.UUID(), nullable=True),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("label", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["graph_revision_id"],
            ["graph_revisions.id"],
            name=op.f("fk_graph_nodes_graph_revision_id_graph_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_nodes")),
        sa.UniqueConstraint(
            "graph_revision_id",
            "stable_key",
            name=op.f("uq_graph_nodes_graph_revision_id_stable_key"),
        ),
    )
    op.create_table(
        "impact_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("change_set_id", sa.UUID(), nullable=False),
        sa.Column("graph_revision_id", sa.UUID(), nullable=False),
        sa.Column("plan_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("plan_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["change_set_id"],
            ["change_sets.id"],
            name=op.f("fk_impact_plans_change_set_id_change_sets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["graph_revision_id"],
            ["graph_revisions.id"],
            name=op.f("fk_impact_plans_graph_revision_id_graph_revisions"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_impact_plans")),
        sa.UniqueConstraint("plan_hash", name=op.f("uq_impact_plans_plan_hash")),
    )
    op.create_table(
        "build_nodes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("build_id", sa.UUID(), nullable=False),
        sa.Column("graph_node_id", sa.UUID(), nullable=False),
        sa.Column("stable_key", sa.String(length=128), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("resolution", sa.String(length=32), nullable=True),
        sa.Column("reason_code", sa.String(length=48), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("selected_attempt_id", sa.UUID(), nullable=True),
        sa.Column("selected_asset_set_hash", sa.String(length=64), nullable=True),
        sa.Column("reuse_proof_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("version", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
            name=op.f("fk_build_nodes_build_id_builds"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["graph_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_build_nodes_graph_node_id_graph_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_build_nodes")),
        sa.UniqueConstraint(
            "build_id", "graph_node_id", name=op.f("uq_build_nodes_build_id_graph_node_id")
        ),
    )
    op.create_index(
        "ix_build_nodes_build_status", "build_nodes", ["build_id", "status"], unique=False
    )
    op.create_index(
        "ix_build_nodes_fingerprint_status", "build_nodes", ["fingerprint", "status"], unique=False
    )
    op.create_table(
        "graph_edges",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("graph_revision_id", sa.UUID(), nullable=False),
        sa.Column("from_node_id", sa.UUID(), nullable=False),
        sa.Column("to_node_id", sa.UUID(), nullable=False),
        sa.Column("input_slot", sa.String(length=64), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("asset_role", sa.String(length=32), nullable=False),
        sa.CheckConstraint("from_node_id <> to_node_id", name=op.f("ck_graph_edges_no_self_edge")),
        sa.ForeignKeyConstraint(
            ["from_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_from_node_id_graph_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["graph_revision_id"],
            ["graph_revisions.id"],
            name=op.f("fk_graph_edges_graph_revision_id_graph_revisions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["to_node_id"],
            ["graph_nodes.id"],
            name=op.f("fk_graph_edges_to_node_id_graph_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_graph_edges")),
        sa.UniqueConstraint(
            "graph_revision_id",
            "to_node_id",
            "input_slot",
            "ordinal",
            name=op.f("uq_graph_edges_graph_revision_id_to_node_id_input_slot_ordinal"),
        ),
    )
    op.create_table(
        "releases",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("build_id", sa.UUID(), nullable=False),
        sa.Column("version_label", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("manifest_asset_id", sa.UUID(), nullable=True),
        sa.Column("verification_asset_id", sa.UUID(), nullable=True),
        sa.Column("approved_by", sa.UUID(), nullable=True),
        sa.Column("approved_at", sa.DateTime(), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("retention_mode", sa.String(length=24), nullable=True),
        sa.Column("retain_until", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_id"],
            ["builds.id"],
            name=op.f("fk_releases_build_id_builds"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_releases_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_releases")),
        sa.UniqueConstraint(
            "project_id", "version_label", name=op.f("uq_releases_project_id_version_label")
        ),
    )
    op.create_table(
        "attempts",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("build_node_id", sa.UUID(), nullable=False),
        sa.Column("attempt_no", sa.Integer(), nullable=False),
        sa.Column("parent_attempt_id", sa.UUID(), nullable=True),
        sa.Column("mechanism", sa.String(length=32), nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=128), nullable=True),
        sa.Column("genblaze_run_id", sa.String(length=128), nullable=True),
        sa.Column("idempotency_key", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("error_class", sa.String(length=24), nullable=True),
        sa.Column("error_code", sa.String(length=64), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("is_injected_fault", sa.Boolean(), nullable=False),
        sa.Column("estimated_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("provider_reported_cost_usd", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_node_id"],
            ["build_nodes.id"],
            name=op.f("fk_attempts_build_node_id_build_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempts")),
        sa.UniqueConstraint(
            "build_node_id", "attempt_no", name=op.f("uq_attempts_build_node_id_attempt_no")
        ),
        sa.UniqueConstraint("idempotency_key", name=op.f("uq_attempts_idempotency_key")),
    )
    op.create_index("ix_attempts_genblaze_run", "attempts", ["genblaze_run_id"], unique=False)
    op.create_index(
        "ix_attempts_node_no", "attempts", ["build_node_id", "attempt_no"], unique=False
    )
    op.create_table(
        "release_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("release_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("logical_path", sa.String(length=512), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_release_assets_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["release_id"],
            ["releases.id"],
            name=op.f("fk_release_assets_release_id_releases"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_release_assets")),
        sa.UniqueConstraint(
            "release_id", "logical_path", name=op.f("uq_release_assets_release_id_logical_path")
        ),
    )
    op.create_table(
        "validations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("build_node_id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=True),
        sa.Column("asset_id", sa.UUID(), nullable=True),
        sa.Column("policy_id", sa.UUID(), nullable=True),
        sa.Column("gate_key", sa.String(length=64), nullable=False),
        sa.Column("gate_version", sa.String(length=8), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("score", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=14, scale=6), nullable=True),
        sa.Column("evidence_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_json", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["build_node_id"],
            ["build_nodes.id"],
            name=op.f("fk_validations_build_node_id_build_nodes"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_validations")),
    )
    op.create_index(
        "ix_validations_node_gate_created",
        "validations",
        ["build_node_id", "gate_key", "created_at"],
        unique=False,
    )
    op.create_table(
        "attempt_assets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("ordinal", sa.Integer(), nullable=False),
        sa.Column("selected", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_attempt_assets_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_assets_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attempt_assets")),
        sa.UniqueConstraint(
            "attempt_id", "role", "ordinal", name=op.f("uq_attempt_assets_attempt_id_role_ordinal")
        ),
    )
    op.create_table(
        "attempt_events",
        sa.Column("sequence", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("attempt_id", sa.UUID(), nullable=False),
        sa.Column("provider_event_type", sa.String(length=64), nullable=False),
        sa.Column("provider_event_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("provider_timestamp", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["attempt_id"],
            ["attempts.id"],
            name=op.f("fk_attempt_events_attempt_id_attempts"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("sequence", name=op.f("pk_attempt_events")),
    )
    op.create_index(
        "ix_attempt_events_attempt_seq", "attempt_events", ["attempt_id", "sequence"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_attempt_events_attempt_seq", table_name="attempt_events")
    op.drop_table("attempt_events")
    op.drop_table("attempt_assets")
    op.drop_index("ix_validations_node_gate_created", table_name="validations")
    op.drop_table("validations")
    op.drop_table("release_assets")
    op.drop_index("ix_attempts_node_no", table_name="attempts")
    op.drop_index("ix_attempts_genblaze_run", table_name="attempts")
    op.drop_table("attempts")
    op.drop_table("releases")
    op.drop_table("graph_edges")
    op.drop_index("ix_build_nodes_fingerprint_status", table_name="build_nodes")
    op.drop_index("ix_build_nodes_build_status", table_name="build_nodes")
    op.drop_table("build_nodes")
    op.drop_table("impact_plans")
    op.drop_table("graph_nodes")
    op.drop_index("ix_builds_project_created", table_name="builds")
    op.drop_table("builds")
    op.drop_table("source_versions")
    op.drop_table("graph_revisions")
    op.drop_table("change_sets")
    op.drop_table("sources")
    op.drop_table("project_revisions")
    op.drop_table("fault_rules")
    op.drop_table("approvals")
    op.drop_table("projects")
    op.drop_table("memberships")
    op.drop_index("ix_b2_object_events_status_time", table_name="b2_object_events")
    op.drop_table("b2_object_events")
    op.drop_table("assets")
    op.drop_index(
        "ix_work_items_claimable",
        table_name="work_items",
        postgresql_where=sa.text("status in ('QUEUED', 'RETRY_WAIT')"),
    )
    op.drop_table("work_items")
    op.drop_table("validation_policies")
    op.drop_table("users")
    op.drop_table("provider_policies")
    op.drop_table("organizations")
    op.drop_table("graph_templates")
    op.drop_index(
        "ix_domain_events_unpublished",
        table_name="domain_events",
        postgresql_where=sa.text("realtime_published_at is null"),
    )
    op.drop_index("ix_domain_events_project_seq", table_name="domain_events")
    op.drop_index("ix_domain_events_build_seq", table_name="domain_events")
    op.drop_table("domain_events")
    op.drop_table("b2_webhook_messages")
    op.drop_index("ix_audit_project_time", table_name="audit_log")
    op.drop_table("audit_log")
    # ### end Alembic commands ###
