"""add durable upload intents

Revision ID: f86e58a65135
Revises: ba9b31eeb0df
Create Date: 2026-08-02 19:27:40.870679
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "f86e58a65135"
down_revision: str | None = "ba9b31eeb0df"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "upload_intents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("source_stable_key", sa.String(length=128), nullable=False),
        sa.Column("original_file_name", sa.String(length=200), nullable=False),
        sa.Column("expected_size_bytes", sa.Integer(), nullable=False),
        sa.Column("declared_mime_type", sa.String(length=128), nullable=False),
        sa.Column("client_sha256", sa.String(length=64), nullable=True),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_asset_id", sa.UUID(), nullable=True),
        sa.Column("completed_source_version_id", sa.UUID(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["completed_asset_id"],
            ["assets.id"],
            name=op.f("fk_upload_intents_completed_asset_id_assets"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["completed_source_version_id"],
            ["source_versions.id"],
            name=op.f("fk_upload_intents_completed_source_version_id_source_versions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_upload_intents_organization_id_organizations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
            name=op.f("fk_upload_intents_project_id_projects"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_upload_intents")),
        sa.UniqueConstraint("object_key", name=op.f("uq_upload_intents_object_key")),
    )
    op.create_index(
        "ix_upload_intents_status_expires", "upload_intents", ["status", "expires_at"], unique=False
    )
    op.alter_column("b2_object_events", "message_id", existing_type=sa.UUID(), nullable=True)
    op.create_foreign_key(
        op.f("fk_source_versions_asset_id_assets"),
        "source_versions",
        "assets",
        ["asset_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_source_versions_asset_id_assets"), "source_versions", type_="foreignkey"
    )
    op.alter_column("b2_object_events", "message_id", existing_type=sa.UUID(), nullable=False)
    op.drop_index("ix_upload_intents_status_expires", table_name="upload_intents")
    op.drop_table("upload_intents")
    # ### end Alembic commands ###


