"""claim index matches order by

Revision ID: 87db4fd02312
Revises: 58c93aa96777
Create Date: 2026-08-02 14:18:22.021408
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision: str = "87db4fd02312"
down_revision: str | None = "58c93aa96777"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_work_items_claimable"),
        table_name="work_items",
        postgresql_where="((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RETRY_WAIT'::character varying])::text[]))",
    )
    op.create_index(
        "ix_work_items_claimable",
        "work_items",
        [sa.literal_column("priority desc"), "available_at"],
        unique=False,
        postgresql_where=sa.text("status in ('QUEUED', 'RETRY_WAIT', 'LEASED')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_work_items_claimable",
        table_name="work_items",
        postgresql_where=sa.text("status in ('QUEUED', 'RETRY_WAIT', 'LEASED')"),
    )
    op.create_index(
        op.f("ix_work_items_claimable"),
        "work_items",
        ["available_at", "priority"],
        unique=False,
        postgresql_where="((status)::text = ANY ((ARRAY['QUEUED'::character varying, 'RETRY_WAIT'::character varying])::text[]))",
    )
    # ### end Alembic commands ###
