"""bind source versions to project revisions

Revision ID: 03e2f8807cda
Revises: f86e58a65135
Create Date: 2026-08-02 19:37:26.349621
"""

from __future__ import annotations

from alembic import op

revision: str = "03e2f8807cda"
down_revision: str | None = "f86e58a65135"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_source_versions_revision_id_project_revisions"),
        "source_versions",
        "project_revisions",
        ["revision_id"],
        ["id"],
        ondelete="RESTRICT",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_source_versions_revision_id_project_revisions"),
        "source_versions",
        type_="foreignkey",
    )
    # ### end Alembic commands ###
