"""claimable index covers expired leases

Revision ID: 58c93aa96777
Revises: a6ef8dba4499
Create Date: 2026-08-02 14:17:11.840639
"""

from __future__ import annotations

revision: str = "58c93aa96777"
down_revision: str | None = "a6ef8dba4499"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
