"""SQLAlchemy declarative base and shared column conventions (PRD §8.1).

Rules this file enforces so individual models cannot drift:

- Primary keys are UUIDs generated by the application, not the database, so an
  object has an identity before it is flushed and correlation IDs can be logged
  before commit.
- Timestamps are `timestamptz` in UTC.
- Money is `numeric(14,6)` with a currency, never a binary float.
- Mutable rows carry `version` for optimistic concurrency.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime
from decimal import Decimal
from typing import Annotated

from sqlalchemy import BigInteger, DateTime, MetaData, Numeric, String, func
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import DeclarativeBase, mapped_column

# Explicit constraint naming so Alembic autogenerate produces stable, reviewable
# migration names instead of database-assigned ones.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    # `column_0_N_name` joins every column in the constraint. `column_0_name`
    # would name both of project_revisions' unique constraints
    # uq_project_revisions_project_id, since both lead with project_id, and the
    # second CREATE fails with DuplicateTable.
    "uq": "uq_%(table_name)s_%(column_0_N_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_N_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)


def utc_now() -> datetime:
    return datetime.now(UTC)


# Reusable column types.
UuidPk = Annotated[
    uuid.UUID, mapped_column(UUID(as_uuid=True), primary_key=True, default=uuid.uuid4)
]
UuidFk = Annotated[uuid.UUID, mapped_column(UUID(as_uuid=True))]
Sha256 = Annotated[str, mapped_column(String(64))]
"""SHA-256 hex. Always computed over bytes this system stored (§8.3.7), never a
provider-supplied claim."""

CreatedAt = Annotated[
    datetime,
    mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False),
]
Json = Annotated[dict, mapped_column(JSONB)]
Money = Annotated[Decimal, mapped_column(Numeric(14, 6))]
"""§8.1: monetary values are numeric(14,6) and never binary float. Unknown cost is
NULL — §5.3 FR-IMPACT-003 requires unknown to stay unknown rather than becoming 0."""

Version = Annotated[int, mapped_column(BigInteger, nullable=False, default=1)]
Sequence = Annotated[int, mapped_column(BigInteger, primary_key=True, autoincrement=True)]
